### ISSUE TITLE
Macro std::thread replacement fails with newer libc++

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-macro#644]
This was first brought to our attention with newer Xcode builds, but it is all newer libc++s.  The issue is that libc++ now forward declares `std::thread` in more places causing conflict. 

No timeline on the fix right now.

**Comment by jpkenny** [comment]
We were doing badly non-standard-compliant things here to make std::thread replacement work. I don't see a workaround except perhaps using the source-to-source tool. I'm just going to disable the feature and the two tests that depend on it for now. It's really just a "nice to have" at this point, since none of the existing skeletons depend on this feature.
