### ISSUE TITLE
Question: In a parallel function, in one thread, is multi-threaded operation performed?

### ISSUE THREAD

**Issue by sunsirui** [sstsimulator/sst-macro#681]
Dear All,
    in a parallel function (eg: MPI_Allgather : Gathers data from all members of a group and sends the data to all members of the group. The MPI_Allgather function is similar to the MPI_Gather function, except that it sends the data to all processes instead of only to the root），
    Assuming that it is currently a follower thread, when sending data to all threads, do you use parallel sending?
    In allgather.cc, the "addDependency()" function pushes the created "SendAction\RecvAction" into the "initial_actions_" collection, and loops the execution of the elements of "initial_actions_" in "void DagCollectiveActor::start()". It doesn't seem to be in parallel, but serial execution?
Thanks to anyone who may shed some light into this.
-sirui

**Comment by jpkenny** [comment]
Hi Sirui,

I think you’re using processes and threads interchangeably, is this correct?

Two things are important to note. First, the communication algorithms can be based on trees, rings, etc, so many sends/recvs can be going on at the same time between various nodes within the system (i.e. the root isn’t just sending every other node a message). Secondly, we’re looking at a discrete event simulator here. Nothing “happens” in the simulation until an event is delivered to a component. So a serial loop can result in a bunch of events being scheduled, and if those events are scheduled at the same time then they happen “in parallel” as far as simulation time is concerned. Only events can advance time.

--Joe

From: sunsirui ***@***.***>
Reply-To: sstsimulator/sst-macro ***@***.***>
Date: Thursday, June 16, 2022 at 1:57 AM
To: sstsimulator/sst-macro ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [sstsimulator/sst-macro] Question: In a parallel function, in one thread, is multi-threaded operation performed? (Issue #681)


Dear All,
in a parallel function (eg: MPI_Allgather : Gathers data from all members of a group and sends the data to all members of the group. The MPI_Allgather function is similar to the MPI_Gather function, except that it sends the data to all processes instead of only to the root），
Assuming that it is currently a follower thread, when sending data to all threads, do you use parallel sending?
In allgather.cc, the "addDependency()" function pushes the created "SendAction\RecvAction" into the "initial_actions_" collection, and loops the execution of the elements of "initial_actions_" in "void DagCollectiveActor::start()". It doesn't seem to be in parallel, but serial execution?
Thanks to anyone who may shed some light into this.
-sirui

**Comment by sunsirui** [comment]
Thank you for your reply!
